// src/workers/stages/codeGenWorker.ts
// Stage 3 — Parallel code generation for all files in the architecture.
// Each file is generated by Ollama with full project context.
// Streams file content to the frontend via Redis pub/sub.

import { Build, type IArchitecture, type IProjectBlueprint } from "../../models/build.model.js";
import { chatStream, extractCode, MODELS } from "../utils/aiClient.js";
import { buildCodeGenPrompt } from "../utils/promptBuilder.js";
import { publishEvent, publishLog } from "../utils/publishEvent.js";
import { trackCost } from "../utils/costTracker.js";
import { bucket } from "../../lib/gcs.js";

// ── Configuration ─────────────────────────────────────────────

/** Max number of files to generate in parallel */
const PARALLEL_BATCH_SIZE = 3;

/** Max retries per file on generation failure */
const MAX_FILE_RETRIES = 2;

// ── Model Selection per File Type ─────────────────────────────

function getModelForFile(filePath: string): string {
    // Config files and seeds use the faster model
    const fastFiles = ["package.json", "Dockerfile", ".env.example", "docker-compose.yml"];
    if (fastFiles.some((f) => filePath.endsWith(f))) return MODELS.FAST;
    if (filePath.includes("/seed/")) return MODELS.FAST;
    if (filePath.includes("/models/")) return MODELS.FAST;

    // Everything else uses the primary coder model
    return MODELS.CODER;
}

// ── Stage 3 Entry Point ───────────────────────────────────────

/**
 * Generate code for all files in the architecture plan.
 * Files are generated in batches for controlled parallelism.
 * Each file is streamed to the frontend and saved to GCS.
 */
export async function runCodeGeneration(buildId: string): Promise<void> {
    const build = await Build.findOne({ buildId });
    if (!build) throw new Error(`Build ${buildId} not found`);

    const architecture = build.architecture;
    const blueprint = build.blueprint;
    if (!architecture) throw new Error(`Build ${buildId} has no architecture — run planning first`);
    if (!blueprint) throw new Error(`Build ${buildId} has no blueprint`);

    const fileTree = architecture.fileTree;
    await publishLog(buildId, `Generating code for ${fileTree.length} files...`);

    // Track already-generated file contents for cross-file context
    const generatedFiles: Map<string, string> = new Map();

    // Process files in batches
    for (let i = 0; i < fileTree.length; i += PARALLEL_BATCH_SIZE) {
        const batch = fileTree.slice(i, i + PARALLEL_BATCH_SIZE);

        const batchPromises = batch.map((filePath) =>
            generateSingleFile(
                buildId,
                filePath,
                architecture,
                blueprint,
                build.input.prompt,
                generatedFiles
            )
        );

        const results = await Promise.allSettled(batchPromises);

        // Collect successful results into context
        for (const result of results) {
            if (result.status === "fulfilled" && result.value) {
                generatedFiles.set(result.value.path, result.value.content);
            }
        }

        // Update overall progress
        const completed = Math.min(i + PARALLEL_BATCH_SIZE, fileTree.length);
        const progressPercent = Math.round(40 + (completed / fileTree.length) * 40); // 40–80 range
        await Build.updateOne(
            { buildId },
            { $set: { progress: progressPercent } }
        );
    }

    await publishLog(buildId, `Code generation complete: ${generatedFiles.size}/${fileTree.length} files generated`);
}

// ── Single File Generator ─────────────────────────────────────

/**
 * Generate code for a single file with streaming.
 */
async function generateSingleFile(
    buildId: string,
    filePath: string,
    architecture: IArchitecture,
    blueprint: IProjectBlueprint,
    userPrompt: string,
    generatedFiles: Map<string, string>,
    retryCount: number = 0
): Promise<{ path: string; content: string } | null> {
    const model = getModelForFile(filePath);

    // Mark file as generating in MongoDB
    await Build.updateOne(
        { buildId, "files.path": filePath },
        { $set: { "files.$.status": "generating" } }
    );

    // Publish file_start event
    await publishEvent(buildId, { type: "file_start", path: filePath });
    await publishLog(buildId, `Generating: ${filePath}`);

    try {
        // Build related files context (limit to prevent prompt explosion)
        const relatedFiles: { path: string; content: string }[] = [];
        const MAX_CONTEXT_FILES = 5;
        let contextCount = 0;

        for (const [genPath, genContent] of generatedFiles) {
            if (contextCount >= MAX_CONTEXT_FILES) break;
            // Include related files (same directory or imported)
            if (isRelatedFile(filePath, genPath)) {
                relatedFiles.push({
                    path: genPath,
                    content: genContent.substring(0, 2000), // Truncate large files
                });
                contextCount++;
            }
        }

        const messages = buildCodeGenPrompt(filePath, architecture, blueprint, userPrompt, relatedFiles);

        // Stream code generation
        const response = await chatStream(
            messages,
            {
                onChunk: async (chunk) => {
                    await publishEvent(buildId, {
                        type: "file_chunk",
                        path: filePath,
                        chunk,
                    });
                },
                onComplete: async (fullContent, usage) => {
                    // Track cost
                    await trackCost(buildId, {
                        inputTokens: usage.inputTokens,
                        outputTokens: usage.outputTokens,
                        model,
                    });
                },
                onError: async (error) => {
                    await publishEvent(buildId, {
                        type: "error",
                        stage: "codegen",
                        file: filePath,
                        message: error.message,
                        retrying: retryCount < MAX_FILE_RETRIES,
                    });
                },
            },
            model
        );

        // Extract clean code (remove markdown fences if present)
        const cleanCode = extractCode(response.content, getLanguageForFile(filePath));

        // Upload to GCS
        const gcsKey = `builds/${buildId}/${filePath}`;
        await uploadCodeToGCS(gcsKey, cleanCode);

        // Update file status in MongoDB
        await Build.updateOne(
            { buildId, "files.path": filePath },
            {
                $set: {
                    "files.$.status": "done",
                    "files.$.s3Key": gcsKey,
                    "files.$.generatedAt": new Date(),
                },
            }
        );

        // Publish file_done event
        await publishEvent(buildId, {
            type: "file_done",
            path: filePath,
            s3Key: gcsKey,
        });

        return { path: filePath, content: cleanCode };
    } catch (error) {
        const message = error instanceof Error ? error.message : String(error);
        console.error(`[CodeGen] Failed to generate ${filePath}:`, message);

        if (retryCount < MAX_FILE_RETRIES) {
            await publishLog(buildId, `Retrying ${filePath} (attempt ${retryCount + 2}/${MAX_FILE_RETRIES + 1})...`, "warn");
            return generateSingleFile(buildId, filePath, architecture, blueprint, userPrompt, generatedFiles, retryCount + 1);
        }

        // Mark file as error after max retries
        await Build.updateOne(
            { buildId, "files.path": filePath },
            {
                $set: {
                    "files.$.status": "error",
                    "files.$.retries": retryCount + 1,
                },
            }
        );

        await publishLog(buildId, `Failed to generate ${filePath} after ${MAX_FILE_RETRIES + 1} attempts`, "error");
        return null;
    }
}

// ── Helpers ───────────────────────────────────────────────────

/**
 * Check if two files are related (same directory or likely import relationship).
 */
function isRelatedFile(currentFile: string, otherFile: string): boolean {
    const currentDir = currentFile.substring(0, currentFile.lastIndexOf("/"));
    const otherDir = otherFile.substring(0, otherFile.lastIndexOf("/"));

    // Same directory
    if (currentDir === otherDir) return true;

    // Model files are relevant to routes/controllers
    if (
        (currentFile.includes("/routes/") || currentFile.includes("/controllers/")) &&
        otherFile.includes("/models/")
    ) return true;

    // Pages/components can reference each other
    if (
        (currentFile.includes("/pages/") || currentFile.includes("/components/")) &&
        (otherFile.includes("/pages/") || otherFile.includes("/components/"))
    ) return true;

    // Config files are always relevant
    if (["package.json", ".env.example"].some((c) => otherFile.endsWith(c))) return true;

    return false;
}

/**
 * Determine the language of a file for code extraction.
 */
function getLanguageForFile(filePath: string): string | undefined {
    const ext = filePath.split(".").pop()?.toLowerCase();
    const langMap: Record<string, string> = {
        js: "javascript",
        jsx: "jsx",
        ts: "typescript",
        tsx: "tsx",
        json: "json",
        css: "css",
        html: "html",
        md: "markdown",
        yaml: "yaml",
        yml: "yaml",
    };
    return ext ? langMap[ext] : undefined;
}

/**
 * Upload generated code to GCS.
 */
async function uploadCodeToGCS(gcsKey: string, content: string): Promise<void> {
    const file = bucket.file(gcsKey);
    await file.save(content, {
        contentType: "text/plain",
        resumable: false,
    });
}
